#!/bin/sh
set -e
tag=pnp4nagios-deb-builder
container=pnp4nagios-deb-build

echo "Building Docker image"
docker build . --tag $tag

echo "Building the deb packages in Docker container"
docker run --name $container $tag

echo "Copying built packages to \"debs\" directory"
mkdir -p debs
docker cp $container:/workdir/dest/. - | tar -C debs/ -xv

echo "Removing the Docker container"
docker rm $container

echo "Removing the generated Docker images"
docker image rm pnp4nagios-deb-builder
